exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex("candidates")
    .del()
    .then(function () {
      // Inserts seed entries
      return knex("candidates").insert([
        // قائمة البناء و العمل دائرة أولى الزرقاء

        {
          name: "سوسن محمد",
          city: "الزرقاء",
          list: "قائمة البناء و العمل",
          circle: "الدائرة الثالثة",
          party: "حزب المستقبل الأردني",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "female",
          type: "كوتا",
          isActivate: true,
          party_votes: 0,
          candidate_national_id: 2068486497,
        },
        {
          name: "جانسيل سامي",
          city: "الزرقاء",
          list: "قائمة البناء و العمل",
          circle: "الدائرة الثالثة",
          party: "حزب المستقبل الأردني",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "female",
          type: "مسيحي",
          isActivate: true,
          party_votes: 0,
          candidate_national_id: 2000000102,
        },
        {
          name: "لورنس قاسم",
          city: "الزرقاء",
          list: "قائمة البناء و العمل",
          circle: "الدائرة الثالثة",
          party: "حزب المستقبل الأردني",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "شيشاني",
          isActivate: true,
          party_votes: 0,
          candidate_national_id: 2000000225,
        },
        {
          name: "خميس حسين",
          city: "الزرقاء",
          list: "قائمة البناء و العمل",
          circle: "الدائرة الثالثة",
          party: "حزب المستقبل الأردني",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "مسلم",
          isActivate: true,
          party_votes: 0,
          candidate_national_id: 1730183497,
        },

        {
          name: "عمار ضيف الله",
          city: "الزرقاء",
          list: "قائمة البناء و العمل",
          circle: "الدائرة الثالثة",
          party: "حزب المستقبل الأردني",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "مسلم",
          isActivate: true,
          party_votes: 0,
          candidate_national_id: 2000003288,
        },

        {
          name: "علي موسى",
          city: "الزرقاء",
          list: "قائمة البناء و العمل",
          circle: "الدائرة الثالثة",
          party: "حزب المستقبل الأردني",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "مسلم",
          isActivate: true,
          party_votes: 0,
          candidate_national_id: 2000600285,
        },

        {
          name: "ضياء فايز",
          city: "الزرقاء",
          list: "قائمة البناء و العمل",
          circle: "الدائرة الثالثة",
          party: "حزب المستقبل الأردني",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "مسلم",
          isActivate: true,
          party_votes: 0,
          candidate_national_id: 2003000278,
        },

        {
          name: "أحمد عيسى",
          city: "الزرقاء",
          list: "قائمة البناء و العمل",
          circle: "الدائرة الثالثة",
          party: "حزب المستقبل الأردني",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "مسلم",
          isActivate: true,
          party_votes: 0,
          candidate_national_id: 2091672238,
        },

        {
          name: "أيمن غسان",
          city: "الزرقاء",
          list: "قائمة البناء و العمل",
          circle: "الدائرة الثالثة",
          party: "حزب المستقبل الأردني",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "مسلم",
          isActivate: true,
          party_votes: 0,
          candidate_national_id: 2000672238,
        },

        {
          name: "عدنان شاهر",
          city: "الزرقاء",
          list: "قائمة البناء و العمل",
          circle: "الدائرة الثالثة",
          party: "حزب المستقبل الأردني",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "مسلم",
          isActivate: true,
          party_votes: 0,
          candidate_national_id: 2008510224,
        },
        // قائمة البناء و العمل دائرة أولى الزرقاء

        {
          name: "لارا مؤيد",
          city: "الزرقاء",
          list: "قائمة البناء و العمل",
          circle: "الدائرة الثالثة",
          party: "حزب المستقبل الأردني",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "female",
          type: "كوتا",
          isActivate: true,
          party_votes: 0,
          candidate_national_id: 2093400162,
        },
        {
          name: "جورج نيكولا",
          city: "الزرقاء",
          list: "قائمة البناء و العمل",
          circle: "الدائرة الثالثة",
          party: "حزب المستقبل الأردني",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "مسيحي",
          isActivate: true,
          party_votes: 0,
          candidate_national_id: 2000248201,
        },
        {
          name: "سيما محمد",
          city: "الزرقاء",
          list: "قائمة البناء و العمل",
          circle: "الدائرة الثالثة",
          party: "حزب المستقبل الأردني",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "female",
          type: "شيشاني",
          isActivate: true,
          party_votes: 0,
          candidate_national_id: 2001970201,
        },
        {
          name: "رعد عصام",
          city: "الزرقاء",
          list: "قائمة البناء و العمل",
          circle: "الدائرة الثالثة",
          party: "حزب المستقبل الأردني",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "مسلم",
          isActivate: true,
          party_votes: 0,
          candidate_national_id: 2008430174,
        },

        {
          name: "حسين عواد",
          city: "الزرقاء",
          list: "قائمة البناء و العمل",
          circle: "الدائرة الثالثة",
          party: "حزب المستقبل الأردني",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "مسلم",
          isActivate: true,
          party_votes: 0,
          candidate_national_id: 2024600162,
        },

        {
          name: "تامر موسى",
          city: "الزرقاء",
          list: "قائمة البناء و العمل",
          circle: "الدائرة الثالثة",
          party: "حزب المستقبل الأردني",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "مسلم",
          isActivate: true,
          party_votes: 0,
          candidate_national_id: 2045000147,
        },

        {
          name: "سامر فريد",
          city: "الزرقاء",
          list: "قائمة البناء و العمل",
          circle: "الدائرة الثالثة",
          party: "حزب المستقبل الأردني",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "مسلم",
          isActivate: true,
          party_votes: 0,
          candidate_national_id: 2068400291,
        },

        {
          name: "سامي سالم",
          city: "الزرقاء",
          list: "قائمة البناء و العمل",
          circle: "الدائرة الثالثة",
          party: "حزب المستقبل الأردني",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "مسلم",
          isActivate: true,
          party_votes: 0,
          candidate_national_id: 2005400246,
        },

        {
          name: "أمير فرحان",
          city: "الزرقاء",
          list: "قائمة البناء و العمل",
          circle: "الدائرة الثالثة",
          party: "حزب المستقبل الأردني",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "مسلم",
          isActivate: true,
          party_votes: 0,
          candidate_national_id: 2050000260,
        },

        {
          name: "أمير فرحان",
          city: "الزرقاء",
          list: "قائمة البناء و العمل",
          circle: "الدائرة الثالثة",
          party: "حزب المستقبل الأردني",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "مسلم",
          isActivate: true,
          party_votes: 0,
          candidate_national_id: 2050000260,
        },

        {
          name: "هادي عمر",
          city: "الزرقاء",
          list: "قائمة البناء و العمل",
          circle: "الدائرة الثالثة",
          party: "حزب المستقبل الأردني",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "مسلم",
          isActivate: true,
          party_votes: 0,
          candidate_national_id: 2060000246,
        },
        {
          name: "أماني محمد",
          city: "الزرقاء",
          list: "قائمة بناة الوطن",
          circle: "الدائرة الثالثة",
          party: "حزب إرادة",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "female",
          type: "كوتا",
          isActivate: true,
          party_votes: 0,
          candidate_national_id: 2008000232,
        },
        {
          name: "اسامة عمر",
          city: "الزرقاء",
          list: "قائمة بناة الوطن",
          circle: "الدائرة الثالثة",
          party: "حزب إرادة",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "مسيحي",
          isActivate: true,
          party_votes: 0,
          candidate_national_id: 2000600222,
        },
        {
          name: "كمال صالح",
          city: "الزرقاء",
          list: "قائمة بناة الوطن",
          circle: "الدائرة الثالثة",
          party: "حزب إرادة",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "شيشاني",
          isActivate: true,
          party_votes: 0,
          candidate_national_id: 2000600229,
        },
        {
          name: "نور الدين فادي",
          city: "الزرقاء",
          list: "قائمة بناة الوطن",
          circle: "الدائرة الثالثة",
          party: "حزب إرادة",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "مسلم",
          isActivate: true,
          party_votes: 0,
          candidate_national_id: 2000600230,
        },

        {
          name: "صلاح مطاوع",
          city: "الزرقاء",
          list: "قائمة بناة الوطن",
          circle: "الدائرة الثالثة",
          party: "حزب إرادة",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "مسلم",
          isActivate: true,
          party_votes: 0,
          candidate_national_id: 2000600231,
        },

        {
          name: "عيد عطا الله",
          city: "الزرقاء",
          list: "قائمة بناة الوطن",
          circle: "الدائرة الثالثة",
          party: "حزب إرادة",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "مسلم",
          isActivate: true,
          party_votes: 0,
          candidate_national_id: 2000600232,
        },

        {
          name: "سمر هاني",
          city: "الزرقاء",
          list: "قائمة بناة الوطن",
          circle: "الدائرة الثالثة",
          party: "حزب إرادة",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "female",
          type: "مسلم",
          isActivate: true,
          party_votes: 0,
          candidate_national_id: 2000600233,
        },

        {
          name: "رافع محمود",
          city: "الزرقاء",
          list: "قائمة بناة الوطن",
          circle: "الدائرة الثالثة",
          party: "حزب إرادة",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "مسلم",
          isActivate: true,
          party_votes: 0,
          candidate_national_id: 2000600234,
        },

        {
          name: "صخر سميح",
          city: "الزرقاء",
          list: "قائمة بناة الوطن",
          circle: "الدائرة الثالثة",
          party: "حزب إرادة",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "مسلم",
          isActivate: true,
          party_votes: 0,
          candidate_national_id: 2000600236,
        },

        {
          name: "مهند فاتح",
          city: "الزرقاء",
          list: "قائمة بناة الوطن",
          circle: "الدائرة الثالثة",
          party: "حزب إرادة",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "مسلم",
          isActivate: true,
          party_votes: 0,
          candidate_national_id: 2000600239,
        },

        // قائمة رؤية دائرة أولى الزرقاء

        {
          name: "دينا جمال",
          city: "الزرقاء",
          list: "قائمة رؤية",
          circle: "الدائرة الثالثة",
          party: "حزب الوحدة الشعبية الديمقراطي الأردني",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "female",
          type: "كوتا",
          isActivate: true,
          party_votes: 0,

          candidate_national_id: 2000600240,
        },
        {
          name: "محمود إياد",
          city: "الزرقاء",
          list: "قائمة رؤية",
          circle: "الدائرة الثالثة",
          party: "حزب الوحدة الشعبية الديمقراطي الأردني",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "مسيحي",
          isActivate: true,
          party_votes: 0,
          candidate_national_id: 2000600241,
        },
        {
          name: "رزق داود",
          city: "الزرقاء",
          list: "قائمة رؤية",
          circle: "الدائرة الثالثة",
          party: "حزب الوحدة الشعبية الديمقراطي الأردني",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "شيشاني",
          isActivate: true,
          party_votes: 0,
          candidate_national_id: 2000600244,
        },
        {
          name: "مايا عيسى",
          city: "الزرقاء",
          list: "قائمة رؤية",
          circle: "الدائرة الثالثة",
          party: "حزب الوحدة الشعبية الديمقراطي الأردني",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "female",
          type: "مسلم",
          isActivate: true,
          party_votes: 0,
          candidate_national_id: 2000600260,
        },

        {
          name: "طارق محمد",
          city: "الزرقاء",
          list: "قائمة رؤية",
          circle: "الدائرة الثالثة",
          party: "حزب الوحدة الشعبية الديمقراطي الأردني",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "مسلم",
          isActivate: true,
          party_votes: 0,
          candidate_national_id: 2000600243,
        },

        {
          name: "مجد الدين عبد الله",
          city: "الزرقاء",
          list: "قائمة رؤية",
          circle: "الدائرة الثالثة",
          party: "حزب الوحدة الشعبية الديمقراطي الأردني",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "مسلم",
          isActivate: true,
          party_votes: 0,
          candidate_national_id: 2000600242,
        },

        {
          name: "زيد حمزة",
          city: "الزرقاء",
          list: "قائمة رؤية",
          circle: "الدائرة الثالثة",
          party: "حزب الوحدة الشعبية الديمقراطي الأردني",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "مسلم",
          isActivate: true,
          party_votes: 0,
          candidate_national_id: 2000600246,
        },

        {
          name: "سعيد حامد",
          city: "الزرقاء",
          list: "قائمة رؤية",
          circle: "الدائرة الثالثة",
          party: "حزب الوحدة الشعبية الديمقراطي الأردني",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "مسلم",
          isActivate: true,
          party_votes: 0,
          candidate_national_id: 2000600249,
        },

        {
          name: "حمود فيصل",
          city: "الزرقاء",
          list: "قائمة رؤية",
          circle: "الدائرة الثالثة",
          party: "حزب الوحدة الشعبية الديمقراطي الأردني",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "مسلم",
          isActivate: true,
          party_votes: 0,
          candidate_national_id: 2000600248,
        },

        {
          name: "وسام ماهر",
          city: "الزرقاء",
          list: "قائمة رؤية",
          circle: "الدائرة الثالثة",
          party: "حزب الوحدة الشعبية الديمقراطي الأردني",
          circle_list: "قائمة الدائرة الثالثة",
          candidate_votes: 0,
          list_votes: 0,
          gender: "male",
          type: "مسلم",
          isActivate: true,
          party_votes: 0,
          candidate_national_id: 2000600250,
        },
      ]);
    });
};
