exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('candidates').del()
    .then(function () {
      // Inserts seed entries
      return knex('candidates').insert(
        // عمان اولى
        [
          {
            "name": "عائشة سالم",
            "city": "عمان",
            "list": "قائمة أ",
            "circle": "الدائرة الثانية",
            "party": null,
            "circle_list": "قائمة الدائرة الثانية",
            "candidate_votes": 0,
            "list_votes": 10,
            "gender": "female",
            "type": "كوتا",
            "isActivate": true,
            "candidate_national_id": 100017,
            "party_votes": 0
          },
          {
            "name": "علي رحمن",
            "city": "إربد",
            "list": "قائمة ب",
            "circle": "الدائرة الثالثة",
            "party": null,
            "circle_list": "قائمة الدائرة الثالثة",
            "candidate_votes": 0,
            "list_votes": 10,
            "gender": "male",
            "type": "مسلم",
            "isActivate": true,
            "candidate_national_id": 100018,
            "party_votes": 0
          },
          {
            "name": "سامية أحمد",
            "city": "الزرقاء",
            "list": "قائمة ج",
            "circle": "الدائرة الأولى",
            "party": null,
            "circle_list": "قائمة الدائرة الأولى",
            "candidate_votes": 10,
            "list_votes": 10,
            "gender": "female",
            "type": "مسيحي",
            "isActivate": true,
            "candidate_national_id": 100019,
            "party_votes": 0
          },
          {
            "name": "خالد محمد",
            "city": "عمان",
            "list": "قائمة أ",
            "circle": "الدائرة الثانية",
            "party": null,
            "circle_list": "قائمة الدائرة الثانية",
            "candidate_votes": 0,
            "list_votes": 10,
            "gender": "male",
            "type": "شيشاني",
            "isActivate": true,
            "candidate_national_id": 100020,
            "party_votes": 0
          },
          {
            "name": "ماروى نبيل",
            "city": "الزرقاء",
            "list": "قائمة ج",
            "circle": "الدائرة الأولى",
            "party": null,
            "circle_list": "قائمة الدائرة الأولى",
            "candidate_votes": 0,
            "list_votes": 10,
            "gender": "female",
            "type": "كوتا",
            "isActivate": true,
            "candidate_national_id": 100021,
            "party_votes": 0
          },
          {
            "name": "طارق علي",
            "city": "عمان",
            "list": "قائمة أ",
            "circle": "الدائرة الثانية",
            "party": null,
            "circle_list": "قائمة الدائرة الثانية",
            "candidate_votes": 0,
            "list_votes": 10,
            "gender": "male",
            "type": "مسلم",
            "isActivate": true,
            "candidate_national_id": 100022,
            "party_votes": 0
          },
          {
            "name": "ليلى سعيد",
            "city": "إربد",
            "list": "قائمة ب",
            "circle": "الدائرة الثالثة",
            "party": null,
            "circle_list": "قائمة الدائرة الثالثة",
            "candidate_votes": 0,
            "list_votes": 10,
            "gender": "female",
            "type": "مسيحي",
            "isActivate": true,
            "candidate_national_id": 100023,
            "party_votes": 0
          },
          {
            "name": "محمد حسين",
            "city": "الزرقاء",
            "list": "قائمة ج",
            "circle": "الدائرة الأولى",
            "party": null,
            "circle_list": "قائمة الدائرة الأولى",
            "candidate_votes": 10,
            "list_votes": 10,
            "gender": "male",
            "type": "شيشاني",
            "isActivate": true,
            "candidate_national_id": 100024,
            "party_votes": 0
          },
          {
            "name": "نوال خالد",
            "city": "عمان",
            "list": "قائمة أ",
            "circle": "الدائرة الثانية",
            "party": "hh",
            "circle_list": "قائمة الدائرة الثانية",
            "candidate_votes": 0,
            "list_votes": 0,
            "gender": "female",
            "type": "كوتا",
            "isActivate": true,
            "candidate_national_id": 100025,
            "party_votes": 20
          },
          {
            "name": "محمد ناصر",
            "city": "إربد",
            "list": "قائمة ب",
            "circle": "الدائرة الثالثة",
            "party": null,
            "circle_list": "قائمة الدائرة الثالثة",
            "candidate_votes": 60,
            "list_votes": 10,
            "gender": "male",
            "type": "مسلم",
            "isActivate": true,
            "candidate_national_id": 100026,
            "party_votes": 0
          },
          {
            "name": "رها عبد الله",
            "city": "الزرقاء",
            "list": "قائمة ج",
            "circle": "الدائرة الأولى",
            "party": null,
            "circle_list": "قائمة الدائرة الأولى",
            "candidate_votes": 10,
            "list_votes": 90,
            "gender": "female",
            "type": "مسيحي",
            "isActivate": true,
            "candidate_national_id": 100027,
            "party_votes": 0
          },
          {
            "name": "خليل أحمد",
            "city": "عمان",
            "list": "قائمة أ",
            "circle": "الدائرة الثانية",
            "party": null,
            "circle_list": "قائمة الدائرة الثانية",
            "candidate_votes": 60,
            "list_votes": 100,
            "gender": "male",
            "type": "شيشاني",
            "isActivate": true,
            "candidate_national_id": 100028,
            "party_votes": 0
          },
          {
            "name": "أحمد صادق",
            "city": "إربد",
            "list": "قائمة ب",
            "circle": "الدائرة الثالثة",
            "party": null,
            "circle_list": "قائمة الدائرة الثالثة",
            "candidate_votes": 10,
            "list_votes": 200,
            "gender": "male",
            "type": "كوتا",
            "isActivate": true,
            "candidate_national_id": 100029,
            "party_votes": 0
          },
          {
            "name": "نور أحمد",
            "city": "الزرقاء",
            "list": "قائمة ج",
            "circle": "الدائرة الأولى",
            "party": null,
            "circle_list": "قائمة الدائرة الأولى",
            "candidate_votes": 0,
            "list_votes": 0,
            "gender": "female",
            "type": "مسلم",
            "isActivate": true,
            "candidate_national_id": 100030,
            "party_votes": 0
          },
          {
            "name": "فادي أحمد",
            "city": "عمان",
            "list": "قائمة أ",
            "circle": "الدائرة الثانية",
            "party": null,
            "circle_list": "قائمة الدائرة الثانية",
            "candidate_votes": 50,
            "list_votes": 100,
            "gender": "male",
            "type": "مسيحي",
            "isActivate": true,
            "candidate_national_id": 100031,
            "party_votes": 0
          },
          {
            "name": "مريم جابر",
            "city": "إربد",
            "list": "قائمة ب",
            "circle": "الدائرة الثالثة",
            "party": null,
            "circle_list": "قائمة الدائرة الثالثة",
            "candidate_votes": 10,
            "list_votes": 10,
            "gender": "female",
            "type": "شيشاني",
            "isActivate": true,
            "candidate_national_id": 100032,
            "party_votes": 0
          },
          {
            "name": "إبراهيم صالح",
            "city": "الزرقاء",
            "list": "قائمة ج",
            "circle": "الدائرة الأولى",
            "party": null,
            "circle_list": "قائمة الدائرة الأولى",
            "candidate_votes": 10,
            "list_votes": 10,
            "gender": "male",
            "type": "كوتا",
            "isActivate": true,
            "candidate_national_id": 100033,
            "party_votes": 0
          },
          {
            "name": "ناديا محمد",
            "city": "عمان",
            "list": "قائمة أ",
            "circle": "الدائرة الثانية",
            "party": null,
            "circle_list": "قائمة الدائرة الثانية",
            "candidate_votes": 10,
            "list_votes": 10,
            "gender": "female",
            "type": "مسلم",
            "isActivate": true,
            "candidate_national_id": 100034,
            "party_votes": 0
          },
          {
            "name": "وليد عبد الله",
            "city": "إربد",
            "list": "قائمة ب",
            "circle": "الدائرة الثالثة",
            "party": null,
            "circle_list": "قائمة الدائرة الثالثة",
            "candidate_votes": 10,
            "list_votes": 10,
            "gender": "male",
            "type": "مسيحي",
            "isActivate": true,
            "candidate_national_id": 100035,
            "party_votes": 0
          },
          {
            "name": "فرح نبيل",
            "city": "الزرقاء",
            "list": "قائمة ج",
            "circle": "الدائرة الأولى",
            "party": null,
            "circle_list": "قائمة الدائرة الأولى",
            "candidate_votes": 0,
            "list_votes": 0,
            "gender": "female",
            "type": "شيشاني",
            "isActivate": true,
            "candidate_national_id": 100036,
            "party_votes": 0
          },
          {
            "name": "خالد محمد",
            "city": "عمان",
            "list": "قائمة أ",
            "circle": "الدائرة الثانية",
            "party": null,
            "circle_list": "قائمة الدائرة الثانية",
            "candidate_votes": 0,
            "list_votes": 0,
            "gender": "male",
            "type": "كوتا",
            "isActivate": true,
            "candidate_national_id": 100037,
            "party_votes": 0
          },
          {
            "name": "سارة علي",
            "city": "إربد",
            "list": "قائمة ب",
            "circle": "الدائرة الثالثة",
            "party": null,
            "circle_list": "قائمة الدائرة الثالثة",
            "candidate_votes": 0,
            "list_votes": 0,
            "gender": "female",
            "type": "مسلم",
            "isActivate": true,
            "candidate_national_id": 100038,
            "party_votes": 0
          },
          {
            "name": "محمد سالم",
            "city": "الزرقاء",
            "list": "قائمة ج",
            "circle": "الدائرة الأولى",
            "party": null,
            "circle_list": "قائمة الدائرة الأولى",
            "candidate_votes": 0,
            "list_votes": 0,
            "gender": "male",
            "type": "مسيحي",
            "isActivate": true,
            "candidate_national_id": 100039,
            "party_votes": 0
          },
          {
            "name": "نور عبد الله",
            "city": "عمان",
            "list": "قائمة أ",
            "circle": "الدائرة الثانية",
            "party": null,
            "circle_list": "قائمة الدائرة الثانية",
            "candidate_votes": 0,
            "list_votes": 0,
            "gender": "female",
            "type": "شيشاني",
            "isActivate": true,
            "candidate_national_id": 100040,
            "party_votes": 0
          },
          {
            "name": "عمر عبد الله",
            "city": "عمان",
            "list": "قائمة سأ",
            "circle": "الدائرة الثانية",
            "party": null,
            "circle_list": "قائمة الدؤائرة الثانية",
            "candidate_votes": 10,
            "list_votes": 10,
            "gender": "female",
            "type": "شيشاني",
            "isActivate": true,
            "candidate_national_id": 100077,
            "party_votes": 0
          }
        ]
        );
    });
};


